### ISSUE TITLE
Different build output on Windows and Linux

### ISSUE THREAD

**Issue by ldz1** [libbitcoin/libbitcoin-build#228] opened 2020-11-21 16:14 UTC
generate.cmd and generate.sh produce different output. Both in terms of file content and number of files.

**Comment by ldz1** [comment] 2020-11-26 22:52
On Windows the build crashes. The problem is primarily caused by this line https://github.com/libbitcoin/libbitcoin-build/blob/9e0f971377010f92ca12b8cccbefb251bb937fb4/gsl.copy_properties.cmd#L69
my.repository is undefined. After fix, the outpoot looks better, but there are further errors that cause the build to fail.

**Comment by evoskuil** [comment] 2020-11-29 03:26
I cannot reproduce a "crash" on Windows, can you be more specific?

**Comment by evoskuil** [comment] 2020-11-29 04:04
```
gsl/4 M: Generating copy_properties.cmd...
(gsl.copy_properties.cmd 70) Undefined expression: my.repository.name
gsl/4 M: Generating generate_artifacts.cmd...
Seeding modules for libbitcoin-blockchain
cmake\FindBitcoin-Database.cmake
1 File(s) copied
cmake\FindBitcoin-Consensus.cmake
1 File(s) copied
Completed population of libbitcoin-blockchain artifacts.
Seeding modules for libbitcoin-client
cmake\FindBitcoin-System.cmake
1 File(s) copied
cmake\FindBitcoin-Protocol.cmake
1 File(s) copied
Completed population of libbitcoin-client artifacts.
Seeding modules for libbitcoin-consensus
cmake\FindSecp256K1.cmake
1 File(s) copied
Completed population of libbitcoin-consensus artifacts.
Seeding modules for libbitcoin-database
cmake\FindBitcoin-System.cmake
1 File(s) copied
Completed population of libbitcoin-database artifacts.
Seeding modules for libbitcoin-explorer
cmake\FindBash-Completion.cmake
1 File(s) copied
cmake\FindBitcoin-Client.cmake
1 File(s) copied
cmake\FindBitcoin-Network.cmake
1 File(s) copied
cmake\FindDl.cmake
1 File(s) copied
Completed population of libbitcoin-explorer artifacts.
Seeding modules for libbitcoin-network
cmake\FindBitcoin-System.cmake
1 File(s) copied
Completed population of libbitcoin-network artifacts.
Seeding modules for libbitcoin-node
cmake\FindBash-Completion.cmake
1 File(s) copied
cmake\FindBitcoin-Blockchain.cmake
1 File(s) copied
cmake\FindBitcoin-Network.cmake
1 File(s) copied
Completed population of libbitcoin-node artifacts.
Seeding modules for libbitcoin-protocol
cmake\FindZmq.cmake
1 File(s) copied
cmake\FindMbedtls.cmake
1 File(s) copied
cmake\FindBitcoin-System.cmake
1 File(s) copied
Completed population of libbitcoin-protocol artifacts.
Seeding modules for libbitcoin-server
cmake\FindBash-Completion.cmake
1 File(s) copied
cmake\FindBitcoin-Node.cmake
1 File(s) copied
cmake\FindBitcoin-Protocol.cmake
1 File(s) copied
Completed population of libbitcoin-server artifacts.
Seeding modules for libbitcoin-system
cmake\FindRt.cmake
1 File(s) copied
cmake\FindIcu-I18N.cmake
1 File(s) copied
cmake\FindDl.cmake
1 File(s) copied
cmake\FindPng.cmake
1 File(s) copied
cmake\FindQrencode.cmake
1 File(s) copied
cmake\FindSecp256K1.cmake
1 File(s) copied
Completed population of libbitcoin-system artifacts.
Successful duplication of modules to output directory.
The system cannot find the batch label specified - pending
props\import\libbitcoin-system.import.props
props\import\libbitcoin-system.import.xml
2 File(s) copied
The system cannot find the batch label specified - pending
props\import\libbitcoin-system.import.props
props\import\libbitcoin-system.import.xml
2 File(s) copied
The system cannot find the batch label specified - pending
props\import\libbitcoin-system.import.props
props\import\libbitcoin-system.import.xml
2 File(s) copied
props\nuget.config
1 File(s) copied
props\build\build_base.bat
1 File(s) copied
The system cannot find the batch label specified - pending
props\import\libbitcoin-consensus.import.props
props\import\libbitcoin-consensus.import.xml
2 File(s) copied
The system cannot find the batch label specified - pending
props\import\libbitcoin-consensus.import.props
props\import\libbitcoin-consensus.import.xml
2 File(s) copied
The system cannot find the batch label specified - pending
props\import\libbitcoin-consensus.import.props
props\import\libbitcoin-consensus.import.xml
2 File(s) copied
props\nuget.config
1 File(s) copied
props\build\build_base.bat
1 File(s) copied
The system cannot find the batch label specified - pending
props\import\libbitcoin-database.import.props
props\import\libbitcoin-database.import.xml
2 File(s) copied
The system cannot find the batch label specified - pending
props\import\libbitcoin-database.import.props
props\import\libbitcoin-database.import.xml
2 File(s) copied
The system cannot find the batch label specified - pending
props\import\libbitcoin-database.import.props
props\import\libbitcoin-database.import.xml
2 File(s) copied
props\nuget.config
1 File(s) copied
props\build\build_base.bat
1 File(s) copied
The system cannot find the batch label specified - pending
props\import\libbitcoin-blockchain.import.props
props\import\libbitcoin-blockchain.import.xml
2 File(s) copied
The system cannot find the batch label specified - pending
props\import\libbitcoin-blockchain.import.props
props\import\libbitcoin-blockchain.import.xml
2 File(s) copied
The system cannot find the batch label specified - pending
props\import\libbitcoin-blockchain.import.props
props\import\libbitcoin-blockchain.import.xml
2 File(s) copied
props\nuget.config
1 File(s) copied
props\build\build_base.bat
1 File(s) copied
The system cannot find the batch label specified - pending
props\project\libbitcoin-blockchain\libbitcoin-blockchain\libbitcoin-blockchain.props
props\project\libbitcoin-blockchain\libbitcoin-blockchain-test\libbitcoin-blockchain-test.props
props\project\libbitcoin-blockchain\libbitcoin-blockchain-tools\libbitcoin-blockchain-tools.props
3 File(s) copied
The system cannot find the batch label specified - pending
props\project\libbitcoin-blockchain\libbitcoin-blockchain\libbitcoin-blockchain.props
props\project\libbitcoin-blockchain\libbitcoin-blockchain-test\libbitcoin-blockchain-test.props
props\project\libbitcoin-blockchain\libbitcoin-blockchain-tools\libbitcoin-blockchain-tools.props
3 File(s) copied
The system cannot find the batch label specified - pending
props\project\libbitcoin-blockchain\libbitcoin-blockchain\libbitcoin-blockchain.props
props\project\libbitcoin-blockchain\libbitcoin-blockchain-test\libbitcoin-blockchain-test.props
props\project\libbitcoin-blockchain\libbitcoin-blockchain-tools\libbitcoin-blockchain-tools.props
3 File(s) copied
```

**Comment by evoskuil** [comment] 2020-11-29 04:28
The `_build.` prefix was omitted from two `_repository` references. This affects the linux shell script generator as well.

```
    for generate.repository by name as _repository
        echo(" Evaluating repository: $(_repository.name)")
        for _repository->install.build as _build where\
            defined(_build.repository) & starts_with(_build.repository, "libbitcoin")
            emit_import_copy(*******._repository, my.path_prefix, _build.repository)
        endfor
        emit_project_props_copy(*******._repository, my.path_prefix)
    endfor
```

**Comment by evoskuil** [comment] 2020-11-29 04:29
With this change all artifacts are copied with the following output:

```
gsl/4 M: Generating copy_properties.cmd...
(gsl.copy_properties.cmd 35) Undefined expression: emit_import_copy.repository
gsl/4 M: Generating generate_artifacts.cmd...
Seeding modules for libbitcoin-blockchain
cmake\FindBitcoin-Database.cmake
1 File(s) copied
cmake\FindBitcoin-Consensus.cmake
1 File(s) copied
Completed population of libbitcoin-blockchain artifacts.
Seeding modules for libbitcoin-client
cmake\FindBitcoin-System.cmake
1 File(s) copied
cmake\FindBitcoin-Protocol.cmake
1 File(s) copied
Completed population of libbitcoin-client artifacts.
Seeding modules for libbitcoin-consensus
cmake\FindSecp256K1.cmake
1 File(s) copied
Completed population of libbitcoin-consensus artifacts.
Seeding modules for libbitcoin-database
cmake\FindBitcoin-System.cmake
1 File(s) copied
Completed population of libbitcoin-database artifacts.
Seeding modules for libbitcoin-explorer
cmake\FindBash-Completion.cmake
1 File(s) copied
cmake\FindBitcoin-Client.cmake
1 File(s) copied
cmake\FindBitcoin-Network.cmake
1 File(s) copied
cmake\FindDl.cmake
1 File(s) copied
Completed population of libbitcoin-explorer artifacts.
Seeding modules for libbitcoin-network
cmake\FindBitcoin-System.cmake
1 File(s) copied
Completed population of libbitcoin-network artifacts.
Seeding modules for libbitcoin-node
cmake\FindBash-Completion.cmake
1 File(s) copied
cmake\FindBitcoin-Blockchain.cmake
1 File(s) copied
cmake\FindBitcoin-Network.cmake
1 File(s) copied
Completed population of libbitcoin-node artifacts.
Seeding modules for libbitcoin-protocol
cmake\FindZmq.cmake
1 File(s) copied
cmake\FindMbedtls.cmake
1 File(s) copied
cmake\FindBitcoin-System.cmake
1 File(s) copied
Completed population of libbitcoin-protocol artifacts.
Seeding modules for libbitcoin-server
cmake\FindBash-Completion.cmake
1 File(s) copied
cmake\FindBitcoin-Node.cmake
1 File(s) copied
cmake\FindBitcoin-Protocol.cmake
1 File(s) copied
Completed population of libbitcoin-server artifacts.
Seeding modules for libbitcoin-system
cmake\FindRt.cmake
1 File(s) copied
cmake\FindIcu-I18N.cmake
1 File(s) copied
cmake\FindDl.cmake
1 File(s) copied
cmake\FindPng.cmake
1 File(s) copied
cmake\FindQrencode.cmake
1 File(s) copied
cmake\FindSecp256K1.cmake
1 File(s) copied
Completed population of libbitcoin-system artifacts.
Successful duplication of modules to output directory.
```

**Comment by evoskuil** [comment] 2020-11-29 04:30
It does not appear that any already checked-in generated artifacts are affected.

**Comment by evoskuil** [comment] 2021-03-01 07:55
Resolved by https://github.com/libbitcoin/libbitcoin-build/pull/233

**Closed by evoskuil** 2021-03-01 07:55 UTC
Labels: bug
